{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-api-controller
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-controller-pod
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
    {{- if ne .Values.networkPolicies.vpcCidr "0.0.0.0/0" }}
    - ipBlock:
        cidr: {{ .Values.networkPolicies.vpcCidr }}
    {{- end }}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-api-updater
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-updater-pod
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
    {{- if ne .Values.networkPolicies.vpcCidr "0.0.0.0/0" }}
    - ipBlock:
        cidr: {{ .Values.networkPolicies.vpcCidr }}
    {{- end }}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-api-cert-upgrader
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-cert-upgrader-pod
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
    {{- if ne .Values.networkPolicies.vpcCidr "0.0.0.0/0" }}
    - ipBlock:
        cidr: {{ .Values.networkPolicies.vpcCidr }}
    {{- end }}
  policyTypes:
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-api-enforcer
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-enforcer-pod
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
    {{- if ne .Values.networkPolicies.vpcCidr "0.0.0.0/0" }}
    - ipBlock:
        cidr: {{ .Values.networkPolicies.vpcCidr }}
    {{- end }}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-api-scanner
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-scanner-pod
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        # ONLY Block requests to cloud metadata IP
        except:
        - 169.254.169.254/32
        {{- end }}
    {{- if ne .Values.networkPolicies.vpcCidr "0.0.0.0/0" }}
    - ipBlock:
        cidr: {{ .Values.networkPolicies.vpcCidr }}
    {{- end }}
  policyTypes:
  - Egress

{{- end }}

