{{- if and .Values.networkPolicies.enabled .Values.bbtests.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-test-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      helm-test: enabled
  egress:
    - to:
      - ipBlock:
          cidr: "0.0.0.0/0"
          # ONLY Block requests to cloud metadata IP
          except:
          - 169.254.169.254/32
  policyTypes:
    - Egress
{{- end }}
