{{- if and .Values.networkPolicies.enabled .Values.monitor.install .Values.monitor.exporter.serviceMonitor.enabled .Values.monitor.exporter.svc.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: neuvector-prometheus-exporter-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: 8068
      protocol: TCP
{{- end }}
