{{- if and .Values.istio.enabled (eq .Values.istio.injection "enabled") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: controller-neuvector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: neuvector-controller-pod
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  {{- if (eq .Values.istio.mtls.mode "STRICT") }}
  portLevelMtls:
    "18300":
      mode: PERMISSIVE
  {{- end }}
{{- end }}
